In [1]:
import numpy as np 
a=np.array([1,3,5,7])
a

array([1, 3, 5, 7])

In [2]:
a.ndim

1

In [3]:
type(a)

numpy.ndarray

In [4]:
a.shape

(4,)

In [6]:
a.size

4

In [7]:
a.max()

7

In [8]:
a.min()

1

In [9]:
a.sum()

16

In [10]:
b=np.array([[1,2,3],[4,5,6]])

In [11]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [12]:
type(b)

numpy.ndarray

In [13]:
b.shape

(2, 3)

In [14]:
b.size

6

In [15]:
b[0,2],b[0,1],b[1,1]

(3, 2, 5)

In [16]:
b[0]

array([1, 2, 3])

In [17]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [18]:
a[:2,1:3]

array([[2, 3],
       [6, 7]])

In [19]:
a[1,3]

8

In [20]:
a[0:,1]

array([ 2,  6, 10])

In [21]:
a[:2,2:]

array([[3, 4],
       [7, 8]])

In [22]:
x=np.array([[1,2],[3,4],[5,6]])
x

array([[1, 2],
       [3, 4],
       [5, 6]])

In [23]:
x[[0,1,2],[0,1,0]]  #[0,1,2==rows] and [0,1,0==columns]

array([1, 4, 5])

# End